# Generated by Django 3.2.6 on 2021-08-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatter',
            old_name='date_created',
            new_name='DateCreated',
        ),
        migrations.RenameField(
            model_name='chatter',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='chatter',
            old_name='name',
            new_name='Name',
        ),
    ]
