# Generated by Django 3.2.6 on 2021-08-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210830_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='Chatter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chatter'),
        ),
        migrations.AddField(
            model_name='message',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chatter'),
        ),
        migrations.AddField(
            model_name='message',
            name='Chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='Tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
