# Generated by Django 3.2.6 on 2021-09-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_category_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, max_length=10, null=True),
        ),
    ]
